import type { createProjectsCanvasCreateService } from "./projects-canvas-create";

export type ProjectsCanvasCreateServiceContract = ReturnType<
  typeof createProjectsCanvasCreateService
>;

export function createProjectsCanvasCreateFacade(
  projectsCanvasCreateService: ProjectsCanvasCreateServiceContract,
) {
  const {
    listProjects,
    listCreateImages,
    generateCreateImages,
    listCreateVideos,
    getCreateImageCapabilities,
    getCreateVideoCapabilities,
    generateCreateVideos,
    deleteCreateImage,
    deleteCreateVideo,
    createProject,
    updateProject,
    getProject,
    getProjectOverview,
    getSettings,
    updateSettings,
    getScript,
    updateScript,
    rewriteScript,
    listAssets,
    getAsset,
    createAsset,
    syncAgentStudioAsset,
    syncAgentStudioCanvasProject,
    updateAsset,
    deleteAsset,
    extractAssets,
    generateAssetImage,
    listStoryboards,
    getStoryboard,
    updateStoryboard,
    deleteStoryboard,
    autoGenerateStoryboards,
    getCreateCreditQuote,
    getProjectCreditQuote,
    generateStoryboardImage,
    listVideos,
    generateVideo,
    listDubbings,
    updateDubbing,
    generateDubbing,
    generateLipSync,
    getTimeline,
    updateTimeline,
    createExport,
    listCanvasProjects,
    getCanvasProject,
    saveCanvasProject,
    deleteCanvasProject,
    listAgentCanvasProjects,
    getAgentCanvasProject,
    saveAgentCanvasProject,
    deleteAgentCanvasProject,
  } = projectsCanvasCreateService;

  return {
    listProjects,
    listCreateImages,
    generateCreateImages,
    listCreateVideos,
    getCreateImageCapabilities,
    getCreateVideoCapabilities,
    generateCreateVideos,
    deleteCreateImage,
    deleteCreateVideo,
    createProject,
    updateProject,
    getProject,
    getProjectOverview,
    getSettings,
    updateSettings,
    getScript,
    updateScript,
    rewriteScript,
    listAssets,
    getAsset,
    createAsset,
    syncAgentStudioAsset,
    syncAgentStudioCanvasProject,
    updateAsset,
    deleteAsset,
    extractAssets,
    generateAssetImage,
    listStoryboards,
    getStoryboard,
    updateStoryboard,
    deleteStoryboard,
    autoGenerateStoryboards,
    getCreateCreditQuote,
    getProjectCreditQuote,
    generateStoryboardImage,
    listVideos,
    generateVideo,
    listDubbings,
    updateDubbing,
    generateDubbing,
    generateLipSync,
    getTimeline,
    updateTimeline,
    createExport,
    listCanvasProjects,
    getCanvasProject,
    saveCanvasProject,
    deleteCanvasProject,
    listAgentCanvasProjects,
    getAgentCanvasProject,
    saveAgentCanvasProject,
    deleteAgentCanvasProject,
  };
}
